// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthColumns holds the columns for the "auth" table.
	AuthColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "access_token", Type: field.TypeString, Nullable: true},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true},
		{Name: "expires_at", Type: field.TypeInt64, Nullable: true},
		{Name: "issued_at", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthTable holds the schema information for the "auth" table.
	AuthTable = &schema.Table{
		Name:       "auth",
		Columns:    AuthColumns,
		PrimaryKey: []*schema.Column{AuthColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "setting_key",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthTable,
		SettingsTable,
	}
)

func init() {
	AuthTable.Annotation = &entsql.Annotation{
		Table: "auth",
	}
	SettingsTable.Annotation = &entsql.Annotation{
		Table: "settings",
	}
}
