// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kula-app/ship/ent/auth"
	"github.com/kula-app/ship/ent/predicate"
)

// AuthUpdate is the builder for updating Auth entities.
type AuthUpdate struct {
	config
	hooks    []Hook
	mutation *AuthMutation
}

// Where appends a list predicates to the AuthUpdate builder.
func (_u *AuthUpdate) Where(ps ...predicate.Auth) *AuthUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *AuthUpdate) SetAccessToken(v string) *AuthUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *AuthUpdate) SetNillableAccessToken(v *string) *AuthUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *AuthUpdate) ClearAccessToken() *AuthUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *AuthUpdate) SetRefreshToken(v string) *AuthUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *AuthUpdate) SetNillableRefreshToken(v *string) *AuthUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *AuthUpdate) ClearRefreshToken() *AuthUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthUpdate) SetExpiresAt(v int64) *AuthUpdate {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthUpdate) SetNillableExpiresAt(v *int64) *AuthUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expires_at" field.
func (_u *AuthUpdate) AddExpiresAt(v int64) *AuthUpdate {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AuthUpdate) ClearExpiresAt() *AuthUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *AuthUpdate) SetIssuedAt(v int64) *AuthUpdate {
	_u.mutation.ResetIssuedAt()
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *AuthUpdate) SetNillableIssuedAt(v *int64) *AuthUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// AddIssuedAt adds value to the "issued_at" field.
func (_u *AuthUpdate) AddIssuedAt(v int64) *AuthUpdate {
	_u.mutation.AddIssuedAt(v)
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *AuthUpdate) ClearIssuedAt() *AuthUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthUpdate) SetUpdatedAt(v time.Time) *AuthUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AuthMutation object of the builder.
func (_u *AuthUpdate) Mutation() *AuthMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := auth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AuthUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auth.Table, auth.Columns, sqlgraph.NewFieldSpec(auth.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(auth.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(auth.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(auth.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(auth.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(auth.FieldExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(auth.FieldExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(auth.FieldExpiresAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(auth.FieldIssuedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedAt(); ok {
		_spec.AddField(auth.FieldIssuedAt, field.TypeInt64, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(auth.FieldIssuedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(auth.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthUpdateOne is the builder for updating a single Auth entity.
type AuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthMutation
}

// SetAccessToken sets the "access_token" field.
func (_u *AuthUpdateOne) SetAccessToken(v string) *AuthUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *AuthUpdateOne) SetNillableAccessToken(v *string) *AuthUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *AuthUpdateOne) ClearAccessToken() *AuthUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *AuthUpdateOne) SetRefreshToken(v string) *AuthUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *AuthUpdateOne) SetNillableRefreshToken(v *string) *AuthUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *AuthUpdateOne) ClearRefreshToken() *AuthUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthUpdateOne) SetExpiresAt(v int64) *AuthUpdateOne {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthUpdateOne) SetNillableExpiresAt(v *int64) *AuthUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expires_at" field.
func (_u *AuthUpdateOne) AddExpiresAt(v int64) *AuthUpdateOne {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AuthUpdateOne) ClearExpiresAt() *AuthUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *AuthUpdateOne) SetIssuedAt(v int64) *AuthUpdateOne {
	_u.mutation.ResetIssuedAt()
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *AuthUpdateOne) SetNillableIssuedAt(v *int64) *AuthUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// AddIssuedAt adds value to the "issued_at" field.
func (_u *AuthUpdateOne) AddIssuedAt(v int64) *AuthUpdateOne {
	_u.mutation.AddIssuedAt(v)
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *AuthUpdateOne) ClearIssuedAt() *AuthUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthUpdateOne) SetUpdatedAt(v time.Time) *AuthUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AuthMutation object of the builder.
func (_u *AuthUpdateOne) Mutation() *AuthMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthUpdate builder.
func (_u *AuthUpdateOne) Where(ps ...predicate.Auth) *AuthUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthUpdateOne) Select(field string, fields ...string) *AuthUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Auth entity.
func (_u *AuthUpdateOne) Save(ctx context.Context) (*Auth, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUpdateOne) SaveX(ctx context.Context) *Auth {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := auth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AuthUpdateOne) sqlSave(ctx context.Context) (_node *Auth, err error) {
	_spec := sqlgraph.NewUpdateSpec(auth.Table, auth.Columns, sqlgraph.NewFieldSpec(auth.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Auth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auth.FieldID)
		for _, f := range fields {
			if !auth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(auth.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(auth.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(auth.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(auth.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(auth.FieldExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(auth.FieldExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(auth.FieldExpiresAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(auth.FieldIssuedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedAt(); ok {
		_spec.AddField(auth.FieldIssuedAt, field.TypeInt64, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(auth.FieldIssuedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(auth.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Auth{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
