// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/kula-app/ship/ent/auth"
	"github.com/kula-app/ship/ent/schema"
	"github.com/kula-app/ship/ent/setting"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authFields := schema.Auth{}.Fields()
	_ = authFields
	// authDescUpdatedAt is the schema descriptor for updated_at field.
	authDescUpdatedAt := authFields[5].Descriptor()
	// auth.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auth.DefaultUpdatedAt = authDescUpdatedAt.Default.(func() time.Time)
	// auth.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auth.UpdateDefaultUpdatedAt = authDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authDescID is the schema descriptor for id field.
	authDescID := authFields[0].Descriptor()
	// auth.DefaultID holds the default value on creation for the id field.
	auth.DefaultID = authDescID.Default.(int)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
}
