// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)
